---
title: "plots"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(dplyr)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A scatter plot of prcp in 2000

```{r}
data("ny_noaa")
ny_noaa|>
  drop_na()|>
  filter(prcp > 0)|>
  separate(date, into = c('year','month'), sep = 4)|>
  mutate(
    month = str_replace(month,'\\-',''))|>
  filter(year == 2000)|>
  plot_ly(
    x = ~month, y = ~prcp,
    type = 'scatter', mode= 'markers', alpha = 0.5
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B bar plot of average prcp from 1981 to 1999

```{r}
ny_noaa|>
  drop_na()|>
  filter(prcp > 0)|>
  separate(date, into = c('year','month'), sep = 4)|>
  mutate(
    month = str_replace(month,'\\-',''))|>
  filter(year < 2000)|>
  group_by(year)|>
  summarise(mean_prcp = mean(prcp))|>
  plot_ly(
    x = ~year, y = ~mean_prcp,
    type = 'bar', mode= 'markers'
  )
```

### Chart C box plot of of prcp from 1981 to 1999

```{r}
ny_noaa|>
  drop_na()|>
  filter(prcp > 0)|>
  separate(date, into = c('year','month'), sep = 4)|>
  mutate(
    month = str_replace(month,'\\-',''))|>
  filter(year < 2000)|>
  group_by(year)|>
  plot_ly(
    x = ~year, y = ~prcp,
    type = 'box', mode= 'viridis'
  )
```

