---
title: "plotly"
author: "Xiangxiong Feng"
date: "2023-11-01"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(dplyr)
```


```{r}
data("ny_noaa")
```

```{r}
  ny_noaa|>
  drop_na()|>
  filter(prcp > 0)|>
  separate(date, into = c('year','month'), sep = 4)|>
  mutate(
    month = str_replace(month,'\\-',''))|>
  filter(year == 2000)|>
  plot_ly(
    x = ~month, y = ~prcp,
    type = 'scatter', mode= 'markers', alpha = 0.5
  )
```


```{r}
  ny_noaa|>
  drop_na()|>
  filter(prcp > 0)|>
  separate(date, into = c('year','month'), sep = 4)|>
  mutate(
    month = str_replace(month,'\\-',''))|>
  filter(year < 2000)|>
  group_by(year)|>
  summarise(mean_prcp = mean(prcp))|>
  plot_ly(
    x = ~year, y = ~mean_prcp,
    type = 'bar', mode= 'markers'
  )
  

```





```{r}
 ny_noaa|>
  drop_na()|>
  filter(prcp > 0)|>
  separate(date, into = c('year','month'), sep = 4)|>
  mutate(
    month = str_replace(month,'\\-',''))|>
  filter(year < 2000)|>
  group_by(year)|>
  plot_ly(
    x = ~year, y = ~prcp,
    type = 'box', mode= 'viridis'
  )
```






